FROM openjdk:17.0.2

EXPOSE 8080

# after 'mvn package' created jar,
# copy file in docker image with new name
COPY /target/spring-app-template*.jar app.jar

# run jar in docker container
CMD [ "java","-jar","app.jar" ]