server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVLET_CONTEXT_PATH:}
    # base path: http://localhost:8080

spring:
  profiles:
    active: ${SPRING_PROFILES:default, dev}
  security:
    user:
      name: test
      password: test
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-app-template?currentSchema=spring_app_template
    username: test
    password: test

  # start database as container:
  # docker run -d --name spring-app-template -e POSTGRES_DB=spring-app-template -e POSTGRES_USER=test -e POSTGRES_PASSWORD=test -p 5432:5432 postgres:16
  # docker ps

  jpa:
    show-sql: true
    properties:
      hibernate:
        # will be created via liquibase
        default_schema: spring_app_template
        jdbc:
          time_zone: UTC
          lob.non_contextual_creation: true
  h2:
    console:
      enabled: true
      path: /h2-console
      # http://localhost:8080/h2-console
  liquibase:
    # reference to resources folder
    change-log: classpath:database/changelog_000_main.yaml
    liquibaseSchema: public
    enabled: ${LIQUIBASE_ENABLED:true}

springdoc:
  api-docs:
    path: "/docs-api"
  swagger-ui:
    path: "/docs-ui"
    # http://localhost:8080/docs-ui

logging:
  level:
    root: ${LOGGING_ROOT_LEVEL:info}

# custom properties
my-section:
  my-prop: my-val # access via class ConfigProperties
  hello-message: ${HELLO_MESSAGE:Hello from default profile with default message} # access via @Value

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:info, health, metrics, beans, prometheus}
      path-mapping:
        health: health
        info: info
        beans: beans
        metrics: metrics
        prometheus: metrics/prometheus
      base-path: /
  endpoint:
    health:
      show-details: ${ACTUATOR_HEALTH_SHOW_DETAILS:always}
      cache:
        time-to-live: ${ACTUATOR_HEALTH_TTL:3000}
      probes:
        enabled: ${ACTUATOR_HEALTH_ENABLED:true}
      group:
        readiness:
          include: "readinessState"
    prometheus:
      enabled: ${ACTUATOR_PROMETHEUS_ENABLED:true}
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
