server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVLET_CONTEXT_PATH:}
    # base path: http://localhost:8080

spring:
  profiles:
    active: ${SPRING_PROFILES:default, dev}
  security:
    user:
      name: test
      password: test

  r2dbc:
    url: r2dbc:h2:mem:///test;DB_CLOSE_DELAY=-1
    properties:
      schema: spring_app_template, PUBLIC
    username: test
    password: test
  liquibase:
    # reference to resources folder
    enabled: true
    change-log: classpath:database/changelog_000_main.yaml
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1 # liquibase needs jdbc
    user: test
    password: test

springdoc:
  api-docs:
    path: "/docs-api"
  swagger-ui:
    path: "/docs-ui"
    # http://localhost:8080/docs-ui

logging:
  level:
    root: ${LOGGING_ROOT_LEVEL:info}
    #org:
      #hibernate: warn
    #liquibase: warn

# custom properties
my-section:
  my-prop: my-val # access via class ConfigProperties
  hello-message: ${HELLO_MESSAGE:Hello from default profile with default message} # access via @Value

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:info, health, metrics, beans, prometheus, h2console}
      path-mapping:
        health: health
        info: info
        beans: beans
        metrics: metrics
        prometheus: metrics/prometheus
      base-path: /
  endpoint:
    health:
      show-details: ${ACTUATOR_HEALTH_SHOW_DETAILS:always}
      cache:
        time-to-live: ${ACTUATOR_HEALTH_TTL:3000}
      probes:
        enabled: ${ACTUATOR_HEALTH_ENABLED:true}
      group:
        readiness:
          include: "readinessState"
    prometheus:
      enabled: ${ACTUATOR_PROMETHEUS_ENABLED:true}
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
