name: Build and push Docker image

on:
  push:
    branches:
      - feat/minimal-gh-action

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build jar with Maven
        run: mvn install -DskipTests

      - name: Copy jar file
        run: cp target/spring-app-template**.jar app.jar

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./Dockerfile_minimal
          tags: ghcr.io/coc-university/spring-app-template:1.0.0

# access docker image locally and run container:
# 1) create personal access token (pat) in github profile developer settings
#   - set checkbox read:packages scope
#   - click button 'Configure SSO'
# 2) login to ghcr: docker login ghcr.io -u your-gh-username -p your-pat
# 3) download image: docker pull ghcr.io/coc-university/spring-app-template:1.0.0
# 4) start container: docker run -d -p 8080:8080 ghcr.io/coc-university/spring-app-template:1.0.0
