name: Build image via maven and push via docker

on:
  push:
    branches:
      - feat/minimal-gh-action

jobs:
  build-and-push-via-maven:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Fetch dependencies from cache to speed up build
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build image with maven
        # no Dockerfile required
        # image name will be set automatically by spring-boot-maven-plugin in pom.xml
        # alternative: set the option '-Dspring-boot.build-image.imageName=ghcr.io/coc-university/spring-app-template:1.0.0-SNAPSHOT'
        run: mvn spring-boot:build-image -DskipTests

      - name: Login to ghcr
        # username: your user in github, password: your personal-access-token from github
        # these values will be set automatically by the pipeline
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to ghcr
        run: docker push ghcr.io/coc-university/spring-app-template:1.0.0-SNAPSHOT
