name: Build and push Docker image

on:
  push:
    branches:
      - feat/minimal-gh-action

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

#      - name: Install Docker Buildx plugin
#        run: |
#          docker buildx install
#          docker buildx create --name mybuilder
#          docker buildx use mybuilder
#
#      - name: Setup Docker Buildx
#        id: buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: List available builders
#        run: docker buildx ls

      - name: Build with Maven
        run: mvn install -DskipTests

      - name: copy jar file
        run: cp target/spring-app-template**.jar app.jar

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/coc-university/spring-app-template:1.0.0

#      - name: Push Docker Image to GitHub Container Registry
#        run: docker push ghcr.io/coc-university/spring-app-template:1.0.0

#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build and push Docker image to GitHub Container Registry
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          push: true
#          tags: ghcr.io/coc-university/spring-app-template:1.0.0
