name: Release Action

on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.releases_created }}
      release_major: ${{ steps.release.outputs.major }}
      release_minor: ${{ steps.release.outputs.minor }}
      release_patch: ${{ steps.release.outputs.patch }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.MASTER_PUSH_TOKEN }}
          release-type: maven
          package-name: spring-app-template

      - name: get version number
        id: release-version
        if: ${{ steps.release.outputs.release_created }}
        run: |
          MAJOR=${{ steps.release.outputs.major }}
          MINOR=${{ steps.release.outputs.minor }}
          PATCH=${{ steps.release.outputs.patch }}
          RELEASE_VERSION=$MAJOR.$MINOR.$PATCH
          echo "Release Version: $RELEASE_VERSION"
          echo "release_version=$RELEASE_VERSION" >>$GITHUB_OUTPUT

      - uses: actions/checkout@v3
      - name: Setup Docker Image Tag
        id: image-tag
        run: |
          SHA=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date '+%Y%m%d%H%M')
          VERSION=${{ steps.release-version.outputs.release_version }}
          echo "SHA: $SHA"
          echo "TIMESTAMP: $TIMESTAMP"
          echo "VERSION: $VERSION"
          echo "image_tag=v${VERSION}-prod-${TIMESTAMP}-${SHA}" >>$GITHUB_OUTPUT

      - name: Print Action Info
        env:
          GITHUB_INFO: ${{ toJson(github) }}
        run: echo "$GITHUB_INFO"

      - name: Build and Push Docker Image
        if: ${{ steps.release.outputs.release_created && success() }}
        run: |
          IMAGE=ghcr.io/coc-ghcr.io/${{ github.repository }}
          TAG=${{ steps.image-tag.outputs.image_tag }}
          echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.actor }} --password-stdin ghcr.io
          docker build -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG
