name: Release Action

on:
  push:
    branches:
      - container-multistage-build
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.releases_created }}
      release_major: ${{ steps.release.outputs.major }}
      release_minor: ${{ steps.release.outputs.minor }}
      release_patch: ${{ steps.release.outputs.patch }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: maven
          package-name: spring-app-template

      - name: get version number
        if: ${{ steps.release.outputs.release_created }}
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "::set-output name=version::$VERSION"
        id: jar-version

      - uses: actions/checkout@v2
      - name: Setup Docker Image Tag
        id: image-tag
        run: |
          SHA=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date '+%Y%m%d%H%M')
          echo "SHA: $SHA"
          echo "TIMESTAMP: $TIMESTAMP"
          echo "::set-output name=image_tag::dev-${TIMESTAMP}-${SHA}"

      #      - name: run SonarQube
      #        if: ${{ steps.release.outputs.release_created }}
      #        run: |
      #          mvn sonar:sonar \
      #          -Dsonar.projectName=spring-app-template \
      #          -Dsonar.projectKey=coc-universe_spring-app-template \
      #          -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }} \
      #          -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }} \
      #          -Dsonar.branch.name=main \
      #          -Dsonar.java.coveragePlugin=jacoco \
      #          -Dsonar.coverage.jacoco.xmlReportPaths=target/jacoco/jacoco.xml

#      - name: build and push docker image
#        if: ${{ steps.release.outputs.release_created }}
#        run: |
#          VERSION=${{ steps.jar-version.outputs.version }}
#          docker build -t spring-app-template:$VERSION . --build-arg RUNNABLE_JAR=app.jar --no-cache
#          echo ${{ secrets.PUSH_PAT }} | docker login ghcr.io -u ${{ secrets.PUSH_USERNAME }} --password-stdin
#          docker tag spring-app-template:$VERSION ghcr.io/coc-university/spring-app-template:$VERSION
#          docker push ghcr.io/coc-university/spring-app-template:$VERSION

      - name: Login to CoC-Registry
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.COCREGISTRY_USER }}
          password: ${{ secrets.COCREGISTRY_TOKEN }}

      - name: Build and push
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/coc-university/spring-app-template:${{ steps.jar-version.outputs.version }}
          build-args: RUNNABLE_JAR=app.jar


      - name: Build Docker Image spring-app-template
        if: success()
        run: |
          image=ghcr.io/coc-ghcr.io/coc-university/spring-app-template
          version=${{ steps.jar-version.outputs.version }}
          tag=${{ steps.image-tag.outputs.image_tag }}
          echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.actor }} --password-stdin ghcr.io
          docker build -t $image:$version:$tag .
          docker push $image:$version:$tag