name: Release Action

on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.releases_created }}
      release_major: ${{ steps.release.outputs.major }}
      release_minor: ${{ steps.release.outputs.minor }}
      release_patch: ${{ steps.release.outputs.patch }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.MASTER_PUSH_TOKEN }}
          release-type: maven
          package-name: ${{ github.event.repository.name }}
          prerelease: true

      - name: get version number
        id: release-version
        if: ${{ steps.release.outputs.release_created }}
        run: |
          MAJOR=${{ steps.release.outputs.major }}
          MINOR=${{ steps.release.outputs.minor }}
          PATCH=${{ steps.release.outputs.patch }}
          RELEASE_VERSION=$MAJOR.$MINOR.$PATCH
          echo "release_version=$RELEASE_VERSION" >>$GITHUB_OUTPUT

      - uses: actions/checkout@v3
      - name: Setup Docker Image Tag without Release
        if: ${{ !steps.release.outputs.release_created && success() }}
        id: image-tag-no-release
        run: |
          IMAGE=ghcr.io/coc-ghcr.io/${{ github.repository }}          
          VERSION=${{ steps.release-version.outputs.release_version }}         
          TIMESTAMP=$(date '+%Y%m%d%H%M')
          SHA=$(git rev-parse --short HEAD)
          echo "SHA: $SHA"
          echo "TIMESTAMP: $TIMESTAMP"
          echo "RELEASE VERSION: $VERSION"
          echo "image_tag=$IMAGE:${TIMESTAMP}-${SHA}" >>$GITHUB_OUTPUT

      - uses: actions/checkout@v3
      - name: Setup Docker Image Tag at Release
        if: ${{ !steps.release.outputs.release_created && success() }}
        id: image-tag-release
        run: |
          IMAGE=ghcr.io/coc-ghcr.io/${{ github.repository }}          
          VERSION=${{ steps.release-version.outputs.release_version }}         
          TIMESTAMP=$(date '+%Y%m%d%H%M')
          SHA=$(git rev-parse --short HEAD)
          echo "SHA: $SHA"
          echo "TIMESTAMP: $TIMESTAMP"
          echo "RELEASE VERSION: $VERSION"
          echo "image_tag=$IMAGE:v${VERSION}" >>$GITHUB_OUTPUT

      - name: Build and Push Docker Image
        if: ${{ steps.release.outputs.release_created && success() }}
        run: |
          TAG=${{ steps.image-tag.outputs.image_tag }}
          echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.actor }} --password-stdin ghcr.io
          docker build -t $TAG .
          docker push $TAG

#      - name: Login to ghcr
#        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.actor }} --password-stdin ghcr.io
#
#      # Build and push Docker Images (amd64 and arm64)
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      - name: Build and push
#        uses: docker/build-push-action@v4
#        with:
#          push: true
#          context: .
#          platforms: linux/amd64,linux/aarch64
#          tags: ${{ steps.image-tag.outputs.image_tag }}
